insert into epist_pedio (onoma_epist_pediou) values ('Mathematics');
insert into epist_pedio (onoma_epist_pediou) values ('Computer and information sciences');
insert into epist_pedio (onoma_epist_pediou) values ('Physical science');
insert into epist_pedio (onoma_epist_pediou) values ('Chemical sciences');
insert into epist_pedio (onoma_epist_pediou) values ('Earth and related Environmental sciences');
insert into epist_pedio (onoma_epist_pediou) values ('Biological science');
insert into epist_pedio (onoma_epist_pediou) values ('Industrial biotechnology');
insert into epist_pedio (onoma_epist_pediou) values ('Agriculture, Forestry, and Fisheries');
insert into epist_pedio (onoma_epist_pediou) values ('Clinical medicine');
insert into epist_pedio (onoma_epist_pediou) values ('Nano-technology');

insert into stelexos (onoma_stelexous) values ('Adriane Hubbis');
insert into stelexos (onoma_stelexous) values ('Flo Noen');
insert into stelexos (onoma_stelexous) values ('Rosabelle Carnson');
insert into stelexos (onoma_stelexous) values ('Lorin Orpen');
insert into stelexos (onoma_stelexous) values ('Etty Pizey');
insert into stelexos (onoma_stelexous) values ('Berna Hazael');
insert into stelexos (onoma_stelexous) values ('Dulcine Lathaye');
insert into stelexos (onoma_stelexous) values ('Ilka Dake');
insert into stelexos (onoma_stelexous) values ('Kathe Friar');
insert into stelexos (onoma_stelexous) values ('Suzanna Barrick');
insert into stelexos (onoma_stelexous) values ('Agata Petti');
insert into stelexos (onoma_stelexous) values ('Lyon Maxfield');
insert into stelexos (onoma_stelexous) values ('Lani Casterot');
insert into stelexos (onoma_stelexous) values ('Mariquilla Robson');
insert into stelexos (onoma_stelexous) values ('Theressa Gladdin');
insert into stelexos (onoma_stelexous) values ('Ginni Imesson');
insert into stelexos (onoma_stelexous) values ('Melamie Keningley');
insert into stelexos (onoma_stelexous) values ('Binnie Aldin');
insert into stelexos (onoma_stelexous) values ('Ardelia Raspin');
insert into stelexos (onoma_stelexous) values ('Gerrie Loadsman');
insert into stelexos (onoma_stelexous) values ('Louis Prosek');
insert into stelexos (onoma_stelexous) values ('Marne Lorand');
insert into stelexos (onoma_stelexous) values ('Ricoriki Regina');
insert into stelexos (onoma_stelexous) values ('Linnie O'' Lone');
insert into stelexos (onoma_stelexous) values ('Ginny Tresise');
insert into stelexos (onoma_stelexous) values ('Libby Rowthorne');
insert into stelexos (onoma_stelexous) values ('Homer Vivien');
insert into stelexos (onoma_stelexous) values ('Candace Bolt');
insert into stelexos (onoma_stelexous) values ('Tamara Kefford');
insert into stelexos (onoma_stelexous) values ('Marcy Gerg');
insert into stelexos (onoma_stelexous) values ('Marlee Petre');
insert into stelexos (onoma_stelexous) values ('Rowney Blencoe');
insert into stelexos (onoma_stelexous) values ('Rogerio Trevett');
insert into stelexos (onoma_stelexous) values ('Joyous Hunnaball');
insert into stelexos (onoma_stelexous) values ('Maison Juanes');
insert into stelexos (onoma_stelexous) values ('Reg Martinet');
insert into stelexos (onoma_stelexous) values ('Matty Owers');
insert into stelexos (onoma_stelexous) values ('Davidson Jefferson');
insert into stelexos (onoma_stelexous) values ('Dannel Rabley');
insert into stelexos (onoma_stelexous) values ('Benjamen Glanfield');
insert into stelexos (onoma_stelexous) values ('Allys Muncey');
insert into stelexos (onoma_stelexous) values ('Pedro Buxey');
insert into stelexos (onoma_stelexous) values ('Farris Dyster');
insert into stelexos (onoma_stelexous) values ('Bald Doyle');
insert into stelexos (onoma_stelexous) values ('Milka Keel');
insert into stelexos (onoma_stelexous) values ('Lilla Jina');
insert into stelexos (onoma_stelexous) values ('Ronald Salvin');
insert into stelexos (onoma_stelexous) values ('Fancy Farlowe');
insert into stelexos (onoma_stelexous) values ('Rebekkah Cescoti');
insert into stelexos (onoma_stelexous) values ('Ephraim Bourton');
insert into stelexos (onoma_stelexous) values ('Ashlie Dudman');
insert into stelexos (onoma_stelexous) values ('Flint Maria');
insert into stelexos (onoma_stelexous) values ('Jessalin Morrice');
insert into stelexos (onoma_stelexous) values ('Jerrilee Briddle');
insert into stelexos (onoma_stelexous) values ('Fey Teaz');
insert into stelexos (onoma_stelexous) values ('Cinnamon Caras');
insert into stelexos (onoma_stelexous) values ('Cody Lapwood');
insert into stelexos (onoma_stelexous) values ('Clerkclaude Mordaunt');
insert into stelexos (onoma_stelexous) values ('Tawsha Spilsbury');
insert into stelexos (onoma_stelexous) values ('Amelina Ferschke');
insert into stelexos (onoma_stelexous) values ('Frankie Kondratenko');
insert into stelexos (onoma_stelexous) values ('Alfreda Valerius');
insert into stelexos (onoma_stelexous) values ('Pauly Rikard');
insert into stelexos (onoma_stelexous) values ('Ancell Hanner');
insert into stelexos (onoma_stelexous) values ('Liv McKinless');
insert into stelexos (onoma_stelexous) values ('Shela D''Alessio');
insert into stelexos (onoma_stelexous) values ('Felicio Ferre');
insert into stelexos (onoma_stelexous) values ('Randell Coping');
insert into stelexos (onoma_stelexous) values ('Belvia Woollcott');
insert into stelexos (onoma_stelexous) values ('Delmore Escalero');
insert into stelexos (onoma_stelexous) values ('Marylee Buttle');
insert into stelexos (onoma_stelexous) values ('Gav Towriss');
insert into stelexos (onoma_stelexous) values ('Stefa Craighill');
insert into stelexos (onoma_stelexous) values ('Lovell Robbings');
insert into stelexos (onoma_stelexous) values ('Jasmine Whitsun');

insert into organismos (syntomografia, onoma, odos, tk, polh) values ('RAS', 'Renner and Sons', '0229 Prentice Pass', 99852, 'Magok');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('RS', 'Reinger-Schiller', '2444 Hanover Crossing', 87456, 'Shanhaiguan');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('MI', 'Mueller Inc', '70341 Amoth Circle', 12387, 'Waso');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('OG', 'Osinski-Gleason', '412 Nova Circle', 56485, 'Telagasari');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('TG', 'Trantow Group', '03455 Waywood Parkway', '50090', 'Santa Clara');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('HD', 'Hintz-Denesik', '2 Duke Street', 12132, 'Santa Rita');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('FS', 'Feeney and Sons', '1 Burning Wood Alley', '88930', 'Benito Juarez');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('KLM', 'Keebler, Lind and Murray', '08351 Orin Place', 'V14', 'Rathdrum');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('WHK', 'Wolf, Hodkiewicz and Kulas', '9846 Saint Paul Place', 35468, 'Jiamaogong');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('BC', 'Balistreri-Connelly', '68259 Corscot Plaza', '368418', 'Bezhta');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('USPC', 'University of the South Pacific Centre', '3498 Morningstar Crossing', '10754', 'Masindi');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('CIS', 'College in Sládkovičovo', '60 Ryan Trail', '81623', 'Bayamo');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('UOM', 'University of Mostar', '890 Coleman Junction', '66127', 'Sarishabari');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('MGWC', 'Miyagi Gakuin Women''s College', '1736 Kennedy Trail', '18689', 'Al Qadmus');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('RH', 'Reinhardt College', '603 Sage Circle', '51770', 'Anle');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('MLUHW', 'Martin-Luther Universität Halle-Wittenberg', '22630 Warrior Circle', '65554', 'Su dong');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('UMCE', 'Universidad Metropolitana de Ciencias de la Educación', '1 Bashford Point', '13458', 'Duiwelskloof');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('UBA', 'Universidad Bicentenaria de Aragua', '9 Nelson Parkway', '30399', 'Lexington');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('TUT', 'Technological University (Taungoo)', '689 Ramsey Place', '64539', 'Pinhais');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('STPU', 'St. Paul University', '571 Coolidge Avenue', '88633', 'Tamiyah');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('WU', 'Willamette University', '19 South Junction', '17528', 'Saint-Brieuc');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('AUE', 'American University in the Emirates', '2 Mariners Cove Point', '25589', 'Ligatne');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('UV', 'Universidad de Valladolid', '682 Declaration Junction', '02906', 'Tantou');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('NAUR', 'National American University, Roseville', '9170 Fieldstone Point', '43360', 'Zibu');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('NUIG', 'National University of Ireland, Galway', '79 Browning Junction', '43376', 'Qiqing');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('GCU', 'GC University', '141 Thompson Pass', '76905', 'Sheze');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('RWC', 'Roberts Wesleyan College', '08 Daystar Circle', '95053', 'Jinqu');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('DYUT', 'Dong Yang University of Technology', '0940 Hoffman Lane', '38399', 'New York City');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('UNI', 'University of Northern Iowa', '6586 Carpenter Court', '65853', 'Sidokumpul');
insert into organismos (syntomografia, onoma, odos, tk, polh) values ('UCI', 'University of California, Irvine', '41018 Oneill Court', '98603', 'Joao Pessoa');